In [1]:
import os, sys; sys.path.append(os.path.dirname(os.getcwd())); ROOT_DIR = '/home/h4zzkr/lab/delOS/'

In [2]:
import pandas as pd
from pathlib import Path

In [3]:
dataset_path = os.path.join(ROOT_DIR, 'data/nlu_data/custom')
snips_path = os.path.join(ROOT_DIR, 'data/nlu_data/snipsai')
df_train = pd.read_csv(os.path.join(snips_path, 'train.csv'))
df_valid = pd.read_csv(os.path.join(snips_path, 'valid.csv'))

In [4]:
df_train['intent_label'].unique()

array(['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic',
       'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent'],
      dtype=object)

In [5]:
df_train[df_train.intent_label == 'GetWeather']

Unnamed: 0 intent_label  \
3715        3715   GetWeather   
3716        3716   GetWeather   
3717        3717   GetWeather   
3718        3718   GetWeather   
3719        3719   GetWeather   
...          ...          ...   
5610        5610   GetWeather   
5611        5611   GetWeather   
5612        5612   GetWeather   
5613        5613   GetWeather   
5614        5614   GetWeather   

                                                  words  \
3715  Tell me the weather forecast for Murone Kōgen ...   
3716  Is it freezing on Jun. the 21st in Apshawa Sou...   
3717  will it be getting warmer in Rainbow Falls Pro...   
3718                      what is the Gearhart forecast   
3719           What is the forecast for DE on 9/11/2035   
...                                                 ...   
5610  What's the weather forecast near to Fern Creek...   
5611  What will the weather be within the same area ...   
5612  Will there be snowfall faraway from Robinson F...   
5613              Tell me the weather forecast for here   
5614              Check the weather for Faroe Islands .   

                                            word_labels  length  
3715  O O O O O O B-geographic_poi I-geographic_poi ...      13  
3716  O O B-condition_temperature O B-timeRange I-ti...      11  
3717  O O O O B-condition_temperature O B-geographic...      10  
3718                                     O O O B-city O       5  
3719                    O O O O O B-state O B-timeRange       8  
...                                                 ...     ...  
5610  O O O O B-spatial_relation O B-city I-city B-t...      11  
5611  O O O O O B-spatial_relation I-spatial_relatio...      16  
5612  O O O B-condition_description B-spatial_relati...       8  
5613                     O O O O O O B-current_location       7  
5614                      O O O O B-country I-country O       7  

[1900 rows x 5 columns]

In [4]:
df_train = pd.read_csv(os.path.join(dataset_path, 'train.csv'))
df_valid = pd.read_csv(os.path.join(dataset_path, 'valid.csv'))

In [7]:
df_train

intent_label                                              words  \
0    turnLightOn                                    it is dark here   
1   turnLightOff                              disable lights please   
2   turnLightOff        turn off the lights upstairs in the bedroom   
3   turnLightOff             also disable lights in the dining room   
4    turnLightOn           enable electric lights inside the office   
5   turnLightOff                   cut the lights down in the house   
6    turnLightOn                                  garden is so dark   
7   turnLightOff            turn off lights in kitchen and basement   
8   turnLightOff                                          light off   
9    turnLightOn                        make some light in bathroom   
10  turnLightOff                     turn this fucking lights off !   
11   turnLightOn                                         make light   
12  turnLightOff                       turn off the bathroom lights   
13  turnLightOff      system , turn off the lightning in the toilet   
14   turnLightOn                                    enable lights !   
15   turnLightOn                                 so dark downstairs   
16  turnLightOff                          hey , shutdown the lights   
17  turnLightOff                  turn off the lights at the stairs   
18   turnLightOn                 turn the lights set in the kitchen   
19   turnLightOn                                   please, light on   
20   turnLightOn    turn on all emergency room lights in the garage   
21  turnLightOff        can you turn off the lights in the garden ?   
22   turnLightOn             enable the illumination in the kitchen   
23  turnLightOff              swtich the lounge's lights off please   
24   turnLightOn                             turn on light upstairs   
25  turnLightOff                                   turn down lights   
26   turnLightOn            enable lights coming through the lounge   
27  turnLightOff                                          off light   
28   turnLightOn                             please make light here   
29  turnLightOff                    can you turn off the light here   
30   turnLightOn                   give me some light in the garage   
31   turnLightOn         enable lights upstairs and in the basement   
32  turnLightOff                               turn off this lights   
33   turnLightOn             also enable lights within the lavatory   
34   turnLightOn                              turn the illumination   
35  turnLightOff         turn off the house lights out in the attic   
36  turnLightOff  i command you to turn off the lights in the to...   
37  turnLightOff                                  system, light off   
38   turnLightOn                 activate lightning in the bathroom   
39  turnLightOff                               bedroom , lights off   
40  turnLightOff  turn off the overhead lights in the guest bedroom   
41  turnLightOff                      turn off the lights next door   
42   turnLightOn                                      on light here   
43   turnLightOn                         turn on the bathroom light   
44   turnLightOn              it is so dark upstairs, turn light on   
45  turnLightOff                            power off lights please   
46   turnLightOn              turn on lights for the little kitchen   
47   turnLightOn                      swtich the garden's lights on   
48  turnLightOff               shutdown the illumination in bedroom   
49   turnLightOn                                      turn light on   
50  turnLightOff      disable the house lights in across the garage   

                                          word_labels  length  
0                            O O O B-location:current       4  
1                                               O O O       3  
2   O O O O B-location:where_room O O B-location:room       8  
3           O O O O O B-location:room I-location:room  

In [8]:
from .base_model import SemanticTagsExtractor
import tensorflow as tf
from transformers import TFBertModel, BertTokenizer
from tensorflow.keras.layers import Dropout, Dense, GlobalAveragePooling1D


class DenseTagsExtractor(tf.keras.Model):
    def __init__(self, intent_num_labels=None, dropout_prob=0.15):
        super().__init__()
        self.dropout = Dropout(dropout_prob)
        self.tag_extractor = Dense(tag_num_labels, name="tag_extractor")

    def call(self, inputs, **kwargs):
        ft_inputs = self.dropout(ft_inputs)
        out = self.intent_classifier(ft_inputs)
        # out = softmax(out)
        return out


ImportError: attempted relative import with no known parent package

In [5]:
slot_names = ["[PAD]"]
slot_names += Path(os.path.join(dataset_path, "vocab.tag")).read_text().strip().splitlines()
slot_map = {}
for label in slot_names:
    slot_map[label] = len(slot_map)
slot_map

{'[PAD]': 0,
 'B-location:room': 1,
 'I-location:room': 2,
 'B-location:where_room': 3,
 'I-location:where_room': 4,
 'B-location:current': 5,
 'I-location:current': 6,
 'O': 7}

In [6]:
import numpy as np
import tensorflow as tf
from sentence_transformers import SentenceTransformer

# ft = SentenceTransformer('distilbert-base-nli-mean-tokens')
# del ft

In [33]:
text = 'Red brown fox is jumping on the trampline'
featurizer.encode(text)[0].shape

(768,)

In [ ]:
'get_max_seq_length',
 'get_sentence_embedding_dimension',
 'get_sentence_features',

In [41]:
ft.get_max_seq_length(), ft.get_sentence_embedding_dimension()

(128, 768)

In [42]:
ft.tokenize(text)

[2417, 2829, 4419, 2003, 8660, 2006, 1996, 12517, 28296, 2063]

In [7]:
from transformers import BertTokenizer

model_name = "bert-base-cased"
tokenizer = BertTokenizer.from_pretrained(model_name)

In [15]:
text_sequences = df_train['words']
slot_names = df_train['word_labels']
max_length = 45

In [8]:
def encode_token_labels(text_sequences, slot_names, featurizer, slot_map, max_length):
    encoded = np.zeros(shape=(len(text_sequences), max_length), dtype=np.int32)
    for i, (text_sequence, word_labels) in enumerate(zip(text_sequences, slot_names)):
        encoded_labels = []
        for word, word_label in zip(text_sequence.split(), word_labels.split()):
            tokens = featurizer.encode(word)
            encoded_labels.append(slot_map[word_label])
            expand_label = word_label.replace("B-", "I-")
            if not expand_label in slot_map:
                expand_label = word_label
            encoded_labels.extend([slot_map[expand_label]] * (len(tokens) - 1))
        encoded[i, 1:len(encoded_labels) + 1] = encoded_labels
    return encoded


slot_train = encode_token_labels(df_train["words"], df_train["word_labels"], tokenizer, slot_map, 128)

In [129]:
def encode_dataset(tokenizer, text_sequences, max_length):
    token_ids = np.zeros(shape=(len(text_sequences), max_length),
                         dtype=np.int32)
    for i, text_sequence in enumerate(text_sequences):
        encoded = tokenizer(text_sequence)
        token_ids[i, 0:len(encoded)] = encoded
    attention_masks = (token_ids != 0).astype(np.int32)
    return {"input_ids": token_ids, "attention_masks": attention_masks}


encoded_train = encode_dataset(b, df_train["words"], 47)
encoded_train["input_ids"][0]

array([2009, 2003, 2601, 2182,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0], dtype=int32)

In [126]:
b = model.tokenize

In [45]:
slot_train[0]

array([0, 7, 7, 7, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [25]:
a = encoded[1]
a

array([0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0], dtype=int32)

# Exp

In [110]:
from sentence_transformers import SentenceTransformer
from sentence_transformers import models
import torch

In [111]:
model = SentenceTransformer('bert-base-nli-mean-tokens')
# model._modules['0'].max_seq_length = 45

In [112]:
enc_train = {'input_ids' : torch.from_numpy(encoded_train['input_ids'][:100]).long().cuda(),
             'attention_mask' : torch.from_numpy(encoded_train['attention_masks'][:100]).long().cuda()
            }

In [113]:
enc_train = encoded_train['input_ids'][:100].tolist()

In [121]:
a = model.encode(enc_train, batch_size=36, output_value='token_embeddings', convert_to_numpy=True, is_pretokenized=True)

In [122]:
np.array(a).shape

(51, 49, 768)

In [13]:
a = model._modules['0'].forward(enc_train)

In [18]:
del a

In [17]:
input_ids = a['input_ids']
attention_mask = a['attention_mask']
token_embeddings = a['token_embeddings']

In [21]:
token_embeddings = token_embeddings.cpu()
input_ids = input_ids.cpu()
attention_mask = attention_mask.cpu()

In [22]:
token_embeddings.shape

torch.Size([51, 45, 768])

In [24]:
dir(model)

['__call__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_eval_during_training',
 '_first_module',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_item_by_idx',
 '_get_name',
 '_get_scheduler',
 '_last_module',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_modules',
 '_named_members',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_version',
 'add_module',
 'apply',
 