In [16]:
import tensorflow as tf
from transformers import TFBertModel, BertTokenizer
from tensorflow.keras.layers import Dropout, Dense, GlobalAveragePooling1D

In [2]:
inp = 'turn off the fucking light please'

In [3]:
model_name = "bert-base-cased"
tokenizer = BertTokenizer.from_pretrained(model_name)

In [4]:
tokenizer.encode(inp)

[101, 1885, 1228, 1103, 8750, 1609, 4268, 102]

In [5]:
from transformers import TFBertModel

base_bert_model = TFBertModel.from_pretrained("bert-base-cased")
base_bert_model.summary()

Some weights of the model checkpoint at bert-base-cased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the ckeckpoint was trained on, you can already use TFBertModel for predictions without further training.


Model: "tf_bert_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bert (TFBertMainLayer)       multiple                  108310272 
Total params: 108,310,272
Trainable params: 108,310,272
Non-trainable params: 0
_________________________________________________________________


In [11]:
inp2 = 'turn off off the fucking light please'

In [12]:
base_bert_model.predict(tokenizer.encode(inp2))

(array([[[ 0.371198  ,  0.3696224 ,  0.25625232, ...,  0.24602285,
           0.47602597,  0.05093362]],
 
        [[-0.47750214, -0.09132154, -0.19665337, ..., -0.27511945,
           0.15225185,  0.871516  ]],
 
        [[-0.74131274, -0.08902054, -0.78558373, ...,  0.01311357,
           0.30869552,  0.45760328]],
 
        ...,
 
        [[ 0.29019377,  0.4982054 ,  0.47340438, ...,  0.14850023,
           0.5591297 ,  0.06993482]],
 
        [[ 0.36887667,  0.3726717 ,  0.25698712, ...,  0.24173726,
           0.4760276 ,  0.0528638 ]],
 
        [[ 0.36996222,  0.36731768,  0.24852875, ...,  0.24976547,
           0.47255707,  0.04378318]]], dtype=float32),
 array([[-0.22683209,  0.5464915 ,  0.99768573, ...,  0.999697  ,
         -0.815754  ,  0.99836254],
        [-0.40892294,  0.29535544,  0.9979004 , ...,  0.9991229 ,
          0.07021762,  0.99812853],
        [-0.53957623,  0.3140151 ,  0.99546015, ...,  0.9991294 ,
          0.7115999 ,  0.991421  ],
        ...,
        [

In [2]:
import numpy as np
a = np.array([0.9, 0.3, 0.4])

In [3]:
np.argsort(a)

array([1, 2, 0])

In [1]:
import os, sys; sys.path.append(os.path.dirname(os.getcwd())); ROOT_DIR = '/home/h4zzkr/lab/delOS/backend'
sys.path.append('/home/h4zzkr/lab/delOS/')

In [2]:
from backend.core.nlu.featurizers.transformer_featurizer import SentenceFeaturizer
import tensorflow as tf
from transformers import TFBertModel, BertTokenizer, DistilBertTokenizer
from tensorflow.keras.layers import Dropout, Dense, GlobalAveragePooling1D

In [3]:
ft = SentenceFeaturizer()
model_name = "distilbert-base-uncased"
tokenizer = DistilBertTokenizer.from_pretrained(model_name)

In [4]:
a = 'get weather for today'
bert_tokenized = tokenizer.encode(a)
tokenized, b, c = ft.featurize(a)

In [7]:
bert_tokenized, tokenized

([101, 2131, 4633, 2005, 2651, 102],
 [[2131,
   4633,
   2005,
   2651,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0]])

In [16]:
ft.featurizer._first_module().tokenizer.decode(bert_tokenized)

'[CLS] get weather for today [SEP]'

In [7]:
tokenizer.decode(bert_tokenized), ft.decode(tokenized)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'